[package]
name = "crust-build"
version = "1.0.0"
authors = ["Marcel Braghetto"]
edition = "2021"
rust-version = "1.59.0"

[dependencies]
clap = "2.33.3"
tempfile = "3.2.0"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.5.12"
